services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laracast-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./storage/logs/php:/var/log/fpm-php.www.log
    networks:
      - laracast-network

  # db:
  #   image: mysql:8.0
  #   container_name: laracast-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  #   networks:
  #     - laracast-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: laracast-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./storage/logs/nginx:/var/log/nginx/
    #   - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - app
    networks:
      - laracast-network

networks:
  laracast-network:
    driver: bridge
